# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.telegram.command.hola:
        class: AppBundle\Commands\HolaCommand
        tags:
            - { name: bo_shurik_telegram_bot.command }

    app.telegram.command.estado:
        class: AppBundle\Commands\EstadoCommand
        tags:
            - { name: bo_shurik_telegram_bot.command }
